# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cparchivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesoactividad',
            name='procesocopia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cparchivos.ProcesoCopia'),
            preserve_default=False,
        ),
    ]
