# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cparchivos', '0002_procesoactividad_procesocopia'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesoactividad',
            name='parametros',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
